version: "3.9"
services:
  product-service:
    container_name: product-service
    build: ./product-service
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - "kafka"
  order-service:
    container_name: order-service
    build: ./order-service
    environment:
      - PORT=8082
      - HOST_PRODUCT_SERVICE=product-service:8081
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - "kafka"
  zookeeper:
    container_name: zookeper
    image: confluentinc/cp-zookeeper:7.1.6
    ports:
      - "22181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    ports: 
      - "29092:29092"
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INNER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - nginx_log_microservices:/var/log/nginx/
      - nginx_data_microservices:/etc/nginx/conf.d/
    depends_on:
      - "product-service"
      - "order-service"

volumes:
  nginx_log_microservices:
    driver: local
  nginx_data_microservices:
    driver: local