version: "3.9"
services:
  product-service:
    container_name: product-service
    build: ./product-service
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    expose:
      - "8081"
  order-service:
    container_name: order-service
    build: ./order-service
    environment:
      - PORT=8082
      - HOST_PRODUCT_SERVICE=product-service:8081
    ports:
      - "8082:8082"
    expose:
      - "8082"
  zookeeper:
    container_name: zookeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.3.1
    ports: 
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - nginx_log_microservices:/var/log/nginx/
      - nginx_data_microservices:/etc/nginx/conf.d/
    depends_on:
      - "product-service"
      - "order-service"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  nginx_log_microservices:
    driver: local
  nginx_data_microservices:
    driver: local