global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'microservices'

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8082']
  
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8081']
  