global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'microservices'
  
rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['localhost:8082']
  
  - job_name: 'product-service'
    static_configs:
      - targets: ['localhost:8081']
  